### ISSUE TITLE
Dialyzer is Cranky

### ISSUE THREAD

**Issue by jherdman** [manukall/feeder_ex#18]
I think the problem is upstream, but if I run Dialyzer on this project I see:

```
lib/feeder_ex.ex:17:no_return
Function parse_file/1 has no local return.
________________________________________________________________________________
lib/feeder_ex.ex:21:no_return
Function parse/1 has no local return.
________________________________________________________________________________
lib/feeder_ex.ex:25:no_return
Function parse!/1 has no local return.
________________________________________________________________________________
```
I'm not really sure how to resolve this, so I figured I'd add an issue in case.

**Comment by michaelnisi** [comment]
Thank you for the good catch. https://github.com/michaelnisi/feeder/commit/7114c62810ed71052226d72fe4a99e737551468c should resolve this.

**Comment by jherdman** [comment]
This is great! Thank you for taking the time to look into this issue.

**Comment by jherdman** [comment]
Closing. This appears to be resolved.
